"""
APEE RAG -- Product Knowledge Base
Embedded product knowledge for ChromaDB vector store.
Used by the RAG engine to provide context for user queries.
"""

PRODUCTS = [
    # GPUs
    {"id":"gpu-rtx-4090","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4090 flagship GPU MSRP $1599 typical price $1500-$1800 best performance Ada Lovelace 24GB GDDR6X.",
     "typical_min":1500,"typical_max":1800,"msrp":1599},
    {"id":"gpu-rtx-4080-super","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4080 Super GPU MSRP $999 typical price $950-$1100 excellent 4K gaming.",
     "typical_min":950,"typical_max":1100,"msrp":999},
    {"id":"gpu-rtx-4070-ti-super","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4070 Ti Super GPU MSRP $799 typical price $750-$900 great 1440p 4K.",
     "typical_min":750,"typical_max":900,"msrp":799},
    {"id":"gpu-rtx-4070-super","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4070 Super GPU MSRP $599 typical price $550-$680 excellent 1440p value.",
     "typical_min":550,"typical_max":680,"msrp":599},
    {"id":"gpu-rtx-4070","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4070 mid GPU MSRP $599 typical price $480-$600 solid 1440p gaming 12GB GDDR6X.",
     "typical_min":480,"typical_max":600,"msrp":599},
    {"id":"gpu-rtx-4060-ti","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4060 Ti GPU MSRP $399 typical price $350-$430 good 1080p 1440p gaming.",
     "typical_min":350,"typical_max":430,"msrp":399},
    {"id":"gpu-rtx-4060","category":"gpu","brand":"NVIDIA",
     "text":"NVIDIA RTX 4060 entry GPU MSRP $299 typical price $260-$320 budget 1080p gaming.",
     "typical_min":260,"typical_max":320,"msrp":299},
    {"id":"gpu-rx-7900-xtx","category":"gpu","brand":"AMD",
     "text":"AMD RX 7900 XTX flagship GPU MSRP $999 typical price $850-$1050 excellent 4K AMD alternative.",
     "typical_min":850,"typical_max":1050,"msrp":999},
    {"id":"gpu-rx-7800-xt","category":"gpu","brand":"AMD",
     "text":"AMD RX 7800 XT GPU MSRP $499 typical price $420-$520 great 1440p value.",
     "typical_min":420,"typical_max":520,"msrp":499},
    {"id":"gpu-rx-7600","category":"gpu","brand":"AMD",
     "text":"AMD RX 7600 budget GPU MSRP $269 typical price $240-$290 good 1080p gaming.",
     "typical_min":240,"typical_max":290,"msrp":269},
    # CPUs
    {"id":"cpu-ryzen-9-7950x","category":"cpu","brand":"AMD",
     "text":"AMD Ryzen 9 7950X flagship CPU MSRP $699 typical $580-$700 16 cores 32 threads workstation.",
     "typical_min":580,"typical_max":700,"msrp":699},
    {"id":"cpu-ryzen-7-7800x3d","category":"cpu","brand":"AMD",
     "text":"AMD Ryzen 7 7800X3D gaming CPU MSRP $449 typical $380-$480 best gaming 3D V-Cache 8 cores.",
     "typical_min":380,"typical_max":480,"msrp":449},
    {"id":"cpu-ryzen-5-7600x","category":"cpu","brand":"AMD",
     "text":"AMD Ryzen 5 7600X CPU MSRP $299 typical $200-$260 6 cores budget gaming.",
     "typical_min":200,"typical_max":260,"msrp":299},
    {"id":"cpu-i9-14900k","category":"cpu","brand":"Intel",
     "text":"Intel Core i9-14900K flagship CPU MSRP $589 typical $350-$500 24 cores high performance.",
     "typical_min":350,"typical_max":500,"msrp":589},
    {"id":"cpu-i7-14700k","category":"cpu","brand":"Intel",
     "text":"Intel Core i7-14700K CPU MSRP $409 typical $320-$420 20 cores great all-around.",
     "typical_min":320,"typical_max":420,"msrp":409},
    {"id":"cpu-i5-14600k","category":"cpu","brand":"Intel",
     "text":"Intel Core i5-14600K CPU MSRP $319 typical $230-$300 14 cores best value Intel gaming.",
     "typical_min":230,"typical_max":300,"msrp":319},
    # Laptops
    {"id":"laptop-macbook-pro-m4","category":"laptop","brand":"Apple",
     "text":"Apple MacBook Pro M4 Pro 14-inch MSRP $1999 typical $1900-$2100 excellent performance battery life.",
     "typical_min":1900,"typical_max":2100,"msrp":1999},
    {"id":"laptop-macbook-air-m3","category":"laptop","brand":"Apple",
     "text":"Apple MacBook Air M3 13-inch ultrabook MSRP $1099 typical $950-$1150 great everyday fanless laptop.",
     "typical_min":950,"typical_max":1150,"msrp":1099},
    {"id":"laptop-dell-xps-15","category":"laptop","brand":"Dell",
     "text":"Dell XPS 15 premium Windows laptop MSRP $1799 typical $1400-$1900 OLED display option.",
     "typical_min":1400,"typical_max":1900,"msrp":1799},
    {"id":"laptop-asus-rog-g16","category":"laptop","brand":"ASUS",
     "text":"ASUS ROG gaming laptop RTX 4070 MSRP $1699 typical $1300-$1700 high refresh gaming.",
     "typical_min":1300,"typical_max":1700,"msrp":1699},
    {"id":"laptop-lenovo-thinkpad-x1","category":"laptop","brand":"Lenovo",
     "text":"Lenovo ThinkPad X1 Carbon business ultrabook MSRP $1699 typical $1200-$1800 lightweight durable.",
     "typical_min":1200,"typical_max":1800,"msrp":1699},
    # Phones
    {"id":"phone-iphone-16-pro","category":"phone","brand":"Apple",
     "text":"Apple iPhone 16 Pro MSRP $999 typical $950-$1050 A18 Pro chip ProMotion display titanium.",
     "typical_min":950,"typical_max":1050,"msrp":999},
    {"id":"phone-iphone-16","category":"phone","brand":"Apple",
     "text":"Apple iPhone 16 MSRP $799 typical $750-$850 A18 chip great camera system.",
     "typical_min":750,"typical_max":850,"msrp":799},
    {"id":"phone-samsung-s25-ultra","category":"phone","brand":"Samsung",
     "text":"Samsung Galaxy S25 Ultra flagship MSRP $1299 typical $1100-$1350 S Pen top Android phone.",
     "typical_min":1100,"typical_max":1350,"msrp":1299},
    {"id":"phone-samsung-s25","category":"phone","brand":"Samsung",
     "text":"Samsung Galaxy S25 MSRP $799 typical $680-$850 Snapdragon 8 Elite great camera.",
     "typical_min":680,"typical_max":850,"msrp":799},
    {"id":"phone-pixel-9-pro","category":"phone","brand":"Google",
     "text":"Google Pixel 9 Pro MSRP $999 typical $850-$1050 best Android camera pure Android experience.",
     "typical_min":850,"typical_max":1050,"msrp":999},
    # Consoles
    {"id":"console-ps5","category":"console","brand":"Sony",
     "text":"Sony PlayStation 5 disc edition MSRP $499 typical $450-$550 top exclusives fast SSD DualSense.",
     "typical_min":450,"typical_max":550,"msrp":499},
    {"id":"console-ps5-slim","category":"console","brand":"Sony",
     "text":"Sony PlayStation 5 Slim MSRP $449 typical $400-$480 smaller form factor same PS5 performance.",
     "typical_min":400,"typical_max":480,"msrp":449},
    {"id":"console-xbox-series-x","category":"console","brand":"Microsoft",
     "text":"Xbox Series X MSRP $499 typical $430-$520 best Xbox performance Game Pass compatible.",
     "typical_min":430,"typical_max":520,"msrp":499},
    {"id":"console-nintendo-switch-oled","category":"console","brand":"Nintendo",
     "text":"Nintendo Switch OLED MSRP $349 typical $320-$380 hybrid handheld home console gaming.",
     "typical_min":320,"typical_max":380,"msrp":349},
    # Headphones
    {"id":"headphones-sony-wh1000xm5","category":"headphones","brand":"Sony",
     "text":"Sony WH-1000XM5 noise-canceling headphones MSRP $399 typical $280-$380 best ANC 30hr battery comfortable.",
     "typical_min":280,"typical_max":380,"msrp":399},
    {"id":"headphones-airpods-pro","category":"headphones","brand":"Apple",
     "text":"Apple AirPods Pro 2nd gen wireless earbuds MSRP $249 typical $180-$250 best for iPhone ANC.",
     "typical_min":180,"typical_max":250,"msrp":249},
    {"id":"headphones-bose-qc45","category":"headphones","brand":"Bose",
     "text":"Bose QuietComfort 45 headphones MSRP $329 typical $220-$300 excellent noise cancellation comfortable.",
     "typical_min":220,"typical_max":300,"msrp":329},
    # Sneakers
    {"id":"sneaker-nb-9060","category":"sneaker","brand":"New Balance",
     "text":"New Balance 9060 lifestyle sneakers MSRP $150 typical $100-$180 popular retro running silhouette many colorways.",
     "typical_min":100,"typical_max":180,"msrp":150},
    {"id":"sneaker-nb-990v6","category":"sneaker","brand":"New Balance",
     "text":"New Balance 990v6 made in USA premium sneakers MSRP $250 typical $220-$280 classic heritage running shoe.",
     "typical_min":220,"typical_max":280,"msrp":250},
    {"id":"sneaker-nike-air-max-90","category":"sneaker","brand":"Nike",
     "text":"Nike Air Max 90 classic lifestyle sneaker MSRP $130 typical $90-$150 iconic visible Air cushioning.",
     "typical_min":90,"typical_max":150,"msrp":130},
    {"id":"sneaker-jordan-1-retro","category":"sneaker","brand":"Jordan",
     "text":"Air Jordan 1 Retro High OG MSRP $180 typical $150-$350 varies by colorway very popular resale.",
     "typical_min":150,"typical_max":350,"msrp":180},
    {"id":"sneaker-adidas-ultraboost","category":"sneaker","brand":"Adidas",
     "text":"Adidas Ultraboost running shoes MSRP $190 typical $130-$200 Boost midsole great everyday wear.",
     "typical_min":130,"typical_max":200,"msrp":190},
    {"id":"sneaker-yeezy-350","category":"sneaker","brand":"Adidas",
     "text":"Adidas Yeezy Boost 350 V2 lifestyle sneaker MSRP $220 typical $200-$400 sought-after frequent restocks.",
     "typical_min":200,"typical_max":400,"msrp":220},
    # Monitors
    {"id":"monitor-lg-oled-27","category":"monitor","brand":"LG",
     "text":"LG 27-inch OLED gaming monitor 240Hz MSRP $799 typical $650-$850 perfect blacks ultra-fast response.",
     "typical_min":650,"typical_max":850,"msrp":799},
    {"id":"monitor-samsung-odyssey-g7","category":"monitor","brand":"Samsung",
     "text":"Samsung Odyssey G7 32-inch 1440p curved 240Hz MSRP $699 typical $500-$700.",
     "typical_min":500,"typical_max":700,"msrp":699},
    {"id":"monitor-dell-ultrasharp-4k","category":"monitor","brand":"Dell",
     "text":"Dell UltraSharp 27-inch 4K USB-C monitor MSRP $699 typical $550-$720 best productivity color accuracy.",
     "typical_min":550,"typical_max":720,"msrp":699},
    # Peripherals
    {"id":"keyboard-logitech-mx-keys","category":"keyboard","brand":"Logitech",
     "text":"Logitech MX Keys wireless keyboard MSRP $119 typical $80-$120 great productivity backlit multi-device.",
     "typical_min":80,"typical_max":120,"msrp":119},
    {"id":"keyboard-keychron-q1","category":"keyboard","brand":"Keychron",
     "text":"Keychron Q1 Pro mechanical keyboard MSRP $199 typical $180-$220 QMK VIA gasket-mounted premium.",
     "typical_min":180,"typical_max":220,"msrp":199},
    {"id":"mouse-logitech-mx-master-3","category":"mouse","brand":"Logitech",
     "text":"Logitech MX Master 3S wireless mouse MSRP $99 typical $75-$105 best productivity MagSpeed scroll.",
     "typical_min":75,"typical_max":105,"msrp":99},
    {"id":"mouse-razer-deathadder-v3","category":"mouse","brand":"Razer",
     "text":"Razer DeathAdder V3 Pro wireless gaming mouse MSRP $159 typical $120-$165 lightweight Focus Pro 30K sensor.",
     "typical_min":120,"typical_max":165,"msrp":159},
    # Stocks
    {"id":"stock-nvda","category":"stock","brand":"NVIDIA",
     "text":"NVIDIA NVDA stock AI chip leader data center GPU market high growth high volatility AI infrastructure.",
     "typical_min":400,"typical_max":1000,"msrp":0},
    {"id":"stock-aapl","category":"stock","brand":"Apple",
     "text":"Apple AAPL stock consumer electronics services stable blue-chip strong ecosystem consistent buybacks.",
     "typical_min":150,"typical_max":240,"msrp":0},
    {"id":"stock-tsla","category":"stock","brand":"Tesla",
     "text":"Tesla TSLA stock EV energy company high volatility growth Elon Musk news EV adoption rates.",
     "typical_min":150,"typical_max":400,"msrp":0},
    {"id":"stock-msft","category":"stock","brand":"Microsoft",
     "text":"Microsoft MSFT stock cloud AI enterprise Azure Office 365 Copilot stable growth.",
     "typical_min":350,"typical_max":500,"msrp":0},
    {"id":"stock-meta","category":"stock","brand":"Meta",
     "text":"Meta Platforms META stock social media Facebook Instagram WhatsApp ad revenue metaverse.",
     "typical_min":300,"typical_max":600,"msrp":0},
    # Crypto
    {"id":"crypto-btc","category":"crypto","brand":"Bitcoin",
     "text":"Bitcoin BTC digital gold largest crypto by market cap store of value institutional adoption.",
     "typical_min":20000,"typical_max":100000,"msrp":0},
    {"id":"crypto-eth","category":"crypto","brand":"Ethereum",
     "text":"Ethereum ETH smart contract platform DeFi NFT ecosystem proof of stake deflationary after merge.",
     "typical_min":1500,"typical_max":5000,"msrp":0},
    {"id":"crypto-sol","category":"crypto","brand":"Solana",
     "text":"Solana SOL fast low-cost blockchain DeFi NFT high throughput Ethereum alternative.",
     "typical_min":50,"typical_max":300,"msrp":0},
]
